on:
  schedule:
    - cron: '30 16 * * *'

name: Automatically Pull from SoftMotions

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        id: pull-latest
        shell: bash
        run: |
          npm install
          echo 'PULL_OUTPUT<<XXXXX_EOF_XXXXX' >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          ./pullLatestFromSoftmotions.js >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo 'XXXXX_EOF_XXXXX' >> $GITHUB_ENV
          LATEST_VERSION=`node -e "console.log(require('./package.json').version)"`
          echo "LATEST_VERSION=v$LATEST_VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Pull latest from softmotions
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: autopull
          delete-branch: true
          title: '${{ env.LATEST_VERSION }} - SoftMotions - Pull in latest changes'
          body: |
            Pull in the latest changes from softmotions
            ${{ env.PULL_OUTPUT }}
          labels: |
            report
            automated pr
          assignees: markwylde
          reviewers: markwylde
          draft: false
