on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    # branches:    
    #   - master

name: Automatically Pull from SoftMotions

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: |
          npm install
          ./pullLatestFromSoftmotions.js

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Pull latest from softmotions
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: master
          delete-branch: true
          title: 'SoftMotions - Pull in latest changes'
          body: |
            Pull in the latest changes from softmotions
          labels: |
            report
            automated pr
          assignees: markwylde
          reviewers: markwylde
          draft: false
