on:
  release:
    types: [created]

name: Upload Release Asset

jobs:
  build-mac:
    name: Build for Mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Delete npm prefix
        run: npm config delete prefix

      - name: Install dependencies
        shell: bash --login {0}
        run: nvm install 16 && nvm use 16

      - name: Build project
        shell: bash --login {0}
        run: |
          npm install --ignore-scripts
          ./installSource.sh

      - name: Run tests
        run: ./node_modules/.bin/ava -s

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./src/ejdb2_node.node
          asset_name: ejdb2_node_x64_darwin_16.x.node
          asset_content_type: application/octet-stream

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [linux-node16, alpine-node16]
        include:
          - type: linux-node16
            image: node:16
            node-version: 16.x
            os: linux
            run: |
              apt-get update
              apt-get install -y make gcc git
              wget -O /cmake-Linux-x86_64.sh https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-x86_64.sh
              mkdir /opt/cmake
              sh /cmake-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
              ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

          - type: alpine-node16
            image: node:16-alpine
            node-version: 16.x
            os: alpine
            run: |
              apk update
              apk add cmake make g++ git
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Build project
        run: ${{ matrix.run }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install
        run: |
          npm install --ignore-scripts
          ./installSource.sh

      - name: Run tests
        run: ./node_modules/.bin/ava -s

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./src/ejdb2_node.node
          asset_name: ejdb2_node_x86_64_${{ matrix.os }}_${{ matrix.node-version }}.node
          asset_content_type: application/octet-stream

  build-linux-aarch64:
    name: Build for Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: dietpi:rpi_armv8_bullseye
          copy_artifact_path: ./src/ejdb2_node.node
          copy_artifact_dest: ./src/ejdb2_node.node
          image_additional_mb: 10240
          commands: |
            curl -sSL https://deb.nodesource.com/setup_16.x | bash -
            apt-get update
            apt-get install -y make clang git nodejs
            node --version
            npm --version
            wget -O /cmake-Linux-aarch64.sh https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-aarch64.sh
            mkdir /opt/cmake
            sh /cmake-Linux-aarch64.sh --prefix=/opt/cmake --skip-license
            ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
            npm i -g yarn
            npm install --ignore-scripts
            ./installSource.sh
            npm run test

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./src/ejdb2_node.node
          asset_name: ejdb2_node_aarch64_linux_16.x.node
          asset_content_type: application/octet-stream

  deploy-npmjs:
    name: Deploy on npmjs.org
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Rename for Github Registry
        run: |
          npm pkg set name="@markwylde/node-ejdb-lite"
          npm install --ignore-scripts

      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          access: public
          token: ${{ secrets.GITHUB_TOKEN }}
