on:
  pull_request:

name: Test ARM Build

jobs:
  deploy-arm-test:
    name: Deploy on npmjs.org
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            apt-get update
            apt-get install -y make gcc git
            wget -O /cmake-Linux-aarch64.sh https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-aarch64.sh
            mkdir /opt/cmake
            sh /cmake-Linux-aarch64.sh --prefix=/opt/cmake --skip-license
            ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            nvm install 16
            npm install --ignore-scripts
            ./installSource.sh
            npm run test
