on:
  pull_request:

name: Test ARM Build

jobs:
  deploy-arm-test:
    name: Deploy ARM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: dietpi:rpi_armv8_bullseye
          copy_artifact_path: ./src/ejdb2_node.node
          copy_artifact_dest: ./src/ejdb2_node.node
          image_additional_mb: 10240
          commands: |
            curl -sSL https://deb.nodesource.com/setup_16.x | bash -
            apt-get update
            apt-get install -y make clang git nodejs
            node --version
            npm --version
            wget -O /cmake-Linux-aarch64.sh https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-aarch64.sh
            mkdir /opt/cmake
            sh /cmake-Linux-aarch64.sh --prefix=/opt/cmake --skip-license
            ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
            npm i -g yarn
            npm install --ignore-scripts
            ./installSource.sh
            npm run test
            echo "chipset is `uname -m`"
            
      - name: List src
        run: ls ./src

